version: '3.7'
services:
  gate-simulator:
    build: ./gate-simulator
    image: gate-simulator:1.0
    ports:
      - '9999:9999'
  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=db_mysql
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgresql:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=db_postgresql
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass